#!/bin/bash
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*01:01_10.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*01:01_11.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*01:01_8.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*01:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*02:01_10.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*02:01_11.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*02:01_8.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*02:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*11:01_10.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*11:01_11.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*11:01_8.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*11:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*23:01_10.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*23:01_11.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*23:01_8.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*23:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*24:02_10.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*24:02_11.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*24:02_8.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-A*24:02_9.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*07:02_10.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*07:02_11.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*07:02_8.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*07:02_9.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*15:02_10.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*15:02_11.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*15:02_8.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*15:02_9.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*40:01_10.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*40:01_11.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*40:01_8.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*40:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*44:02_10.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*44:02_11.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*44:02_8.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*44:02_9.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*51:01_10.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*51:01_11.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*51:01_8.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_casan/HLA-B*51:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/dataset/Anthem_dataset/test_data.txt
python /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/test.py /data1/wuguojia/data/mhc_benchmark/tools/CapsNet-MHC/codes/Anthem_codes/Anthem_test/config.json
