#!/bin/bash
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*01:01_10.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*01:01_10.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*01:01_11.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*01:01_11.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*01:01_8.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*01:01_8.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*01:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*01:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*02:01_10.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*02:01_10.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*02:01_11.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*02:01_11.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*02:01_8.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*02:01_8.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*02:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*02:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*11:01_10.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*11:01_10.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*11:01_11.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*11:01_11.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*11:01_8.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*11:01_8.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*11:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*11:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*23:01_10.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*23:01_10.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*23:01_11.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*23:01_11.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*23:01_8.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*23:01_8.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*23:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*23:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*24:02_10.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*24:02_10.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*24:02_11.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*24:02_11.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*24:02_8.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*24:02_8.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*24:02_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-A*24:02_9.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*07:02_10.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*07:02_10.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*07:02_11.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*07:02_11.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*07:02_8.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*07:02_8.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*07:02_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*07:02_9.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*15:02_10.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*15:02_10.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*15:02_11.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*15:02_11.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*15:02_8.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*15:02_8.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*15:02_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*15:02_9.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*40:01_10.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*40:01_10.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*40:01_11.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*40:01_11.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*40:01_8.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*40:01_8.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*40:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*40:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*44:02_10.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*44:02_10.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*44:02_11.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*44:02_11.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*44:02_8.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*44:02_8.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*44:02_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*44:02_9.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*51:01_10.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*51:01_10.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*51:01_11.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*51:01_11.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*51:01_8.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*51:01_8.txt
cp /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*51:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/speedbase/txt_deepnetbim/HLA-B*51:01_9.txt
