#!/bin/bash
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*01:01_10.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*01:01_11.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*01:01_8.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*01:01_9.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*02:01_10.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*02:01_11.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*02:01_8.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*02:01_9.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*11:01_10.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*11:01_11.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*11:01_8.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*11:01_9.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*23:01_10.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*23:01_11.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*23:01_8.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*23:01_9.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*24:02_10.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*24:02_11.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*24:02_8.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-A*24:02_9.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*07:02_10.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*07:02_11.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*07:02_8.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*07:02_9.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*15:02_10.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*15:02_11.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*15:02_8.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*15:02_9.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*40:01_10.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*40:01_11.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*40:01_8.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*40:01_9.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*44:02_10.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*44:02_11.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*44:02_8.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*44:02_9.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*51:01_10.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*51:01_11.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*51:01_8.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
deephlapan -F /data1/wuguojia/data/mhc_benchmark/speedbase/csv_deephlapan/HLA-B*51:01_9.csv -O /data1/wuguojia/data/mhc_benchmark/speedbase/result
