#!/bin/bash
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*01:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*01:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*01:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*01:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*01:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*01:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*01:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*01:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*02:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*02:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*02:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*02:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*02:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*02:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*02:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*02:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*11:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*11:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*11:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*11:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*11:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*11:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*11:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*11:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*23:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*23:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*23:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*23:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*23:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*23:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*23:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*23:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*24:02_10.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*24:02_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*24:02_11.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*24:02_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*24:02_8.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*24:02_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-A*24:02_9.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-A*24:02_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*07:02_10.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*07:02_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*07:02_11.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*07:02_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*07:02_8.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*07:02_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*07:02_9.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*07:02_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*15:02_10.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*15:02_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*15:02_11.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*15:02_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*15:02_8.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*15:02_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*15:02_9.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*15:02_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*40:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*40:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*40:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*40:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*40:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*40:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*40:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*40:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*44:02_10.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*44:02_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*44:02_11.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*44:02_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*44:02_8.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*44:02_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*44:02_9.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*44:02_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*51:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*51:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*51:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*51:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*51:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*51:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/speedbase/csv/HLA-B*51:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/speedbase/result/HLA-B*51:01_9.csv
