#!/bin/bash
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*01:01_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*01:01_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 10 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*01:01_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*01:01_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 11 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*01:01_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*01:01_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 8 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*01:01_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*01:01_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 9 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*02:01_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*02:01_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 10 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*02:01_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*02:01_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 11 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*02:01_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*02:01_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 8 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*02:01_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*02:01_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 9 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*11:01_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*11:01_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 10 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*11:01_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*11:01_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 11 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*11:01_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*11:01_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 8 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*11:01_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*11:01_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 9 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*23:01_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*23:01_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 10 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*23:01_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*23:01_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 11 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*23:01_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*23:01_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 8 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*23:01_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*23:01_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 9 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*24:02_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*24:02_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 10 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*24:02_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*24:02_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 11 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*24:02_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*24:02_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 8 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-A*24:02_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-A*24:02_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 9 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*07:02_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*07:02_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 10 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*07:02_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*07:02_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 11 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*07:02_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*07:02_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 8 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*07:02_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*07:02_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 9 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*15:02_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*15:02_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 10 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*15:02_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*15:02_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 11 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*15:02_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*15:02_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 8 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*15:02_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*15:02_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 9 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*40:01_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*40:01_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 10 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*40:01_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*40:01_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 11 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*40:01_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*40:01_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 8 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*40:01_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*40:01_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 9 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*44:02_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*44:02_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 10 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*44:02_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*44:02_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 11 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*44:02_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*44:02_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 8 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*44:02_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*44:02_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 9 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*51:01_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*51:01_10.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 10 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*51:01_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*51:01_11.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 11 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*51:01_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*51:01_8.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 8 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
cp /data1/wuguojia/data/mhc_benchmark/speedbase/fasta/HLA-B*51:01_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/peptides.fasta
cp /data1/wuguojia/data/mhc_benchmark/speedbase/HLA_fasta/HLA-B*51:01_9.fasta /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/hlas.fasta
python /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py --peptide_file "peptides.fasta" --HLA_file "hlas.fasta" --threshold 0.5 --cut_length 9 --cut_peptide False --output_dir /data1/wuguojia/data/mhc_benchmark/tools/TransPHLA-AOMP/TransPHLA-AOMP/results/
