#!/bin/bash
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*01:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*01:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*01:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*01:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*01:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*01:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*01:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*01:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*02:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*02:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*02:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*02:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*02:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*02:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*02:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*02:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*03:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*03:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*03:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*03:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*03:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*03:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*03:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*03:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*11:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*11:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*11:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*11:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*11:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*11:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*11:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*11:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*23:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*23:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*23:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*23:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*23:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*23:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*23:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*23:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*24:02_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*24:02_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*24:02_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*24:02_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*24:02_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*24:02_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*24:02_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*24:02_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*25:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*25:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*25:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*25:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*25:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*25:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*25:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*25:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*26:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*26:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*26:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*26:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*26:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*26:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*26:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*26:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*30:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*30:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*30:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*30:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*30:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*30:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*30:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*30:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*32:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*32:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*32:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*32:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*32:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*32:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*32:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*32:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*33:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*33:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*33:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*33:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*33:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*33:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*33:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*33:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*33:03_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*33:03_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*33:03_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*33:03_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*33:03_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*33:03_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*33:03_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*33:03_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*66:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*66:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*66:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*66:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*66:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*66:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*66:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*66:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*68:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*68:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*68:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*68:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*68:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*68:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-A*68:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-A*68:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*07:02_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*07:02_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*07:02_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*07:02_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*07:02_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*07:02_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*07:02_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*07:02_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*08:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*08:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*08:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*08:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*08:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*08:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*08:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*08:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*13:02_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*13:02_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*13:02_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*13:02_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*13:02_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*13:02_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*13:02_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*13:02_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*14:02_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*14:02_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*14:02_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*14:02_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*14:02_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*14:02_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*14:02_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*14:02_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*15:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*15:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*15:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*15:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*15:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*15:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*15:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*15:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*15:02_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*15:02_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*15:02_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*15:02_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*15:02_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*15:02_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*15:02_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*15:02_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*18:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*18:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*18:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*18:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*18:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*18:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*18:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*18:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*27:05_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*27:05_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*27:05_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*27:05_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*27:05_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*27:05_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*27:05_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*27:05_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*27:09_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*27:09_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*27:09_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*27:09_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*27:09_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*27:09_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*27:09_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*27:09_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*35:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*35:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*35:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*35:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*35:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*35:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*35:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*35:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*35:02_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*35:02_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*35:02_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*35:02_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*35:02_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*35:02_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*35:02_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*35:02_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*35:03_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*35:03_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*35:03_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*35:03_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*35:03_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*35:03_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*35:03_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*35:03_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*38:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*38:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*38:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*38:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*38:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*38:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*38:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*38:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*39:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*39:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*39:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*39:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*39:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*39:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*39:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*39:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*40:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*40:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*40:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*40:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*40:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*40:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*40:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*40:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*40:02_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*40:02_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*40:02_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*40:02_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*40:02_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*40:02_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*40:02_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*40:02_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*41:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*41:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*41:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*41:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*41:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*41:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*41:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*41:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*44:02_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*44:02_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*44:02_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*44:02_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*44:02_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*44:02_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*44:02_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*44:02_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*44:03_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*44:03_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*44:03_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*44:03_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*44:03_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*44:03_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*44:03_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*44:03_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*49:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*49:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*49:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*49:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*49:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*49:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*49:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*49:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*51:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*51:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*51:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*51:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*51:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*51:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*51:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*51:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*53:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*53:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*53:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*53:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*53:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*53:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*53:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*53:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*57:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*57:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*57:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*57:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*57:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*57:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*57:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*57:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*58:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*58:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*58:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*58:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*58:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*58:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-B*58:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-B*58:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*03:04_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*03:04_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*03:04_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*03:04_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*03:04_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*03:04_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*03:04_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*03:04_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*04:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*04:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*04:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*04:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*04:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*04:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*04:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*04:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*05:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*05:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*05:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*05:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*05:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*05:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*05:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*05:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*07:01_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*07:01_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*07:01_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*07:01_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*07:01_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*07:01_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*07:01_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*07:01_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*08:02_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*08:02_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*08:02_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*08:02_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*08:02_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*08:02_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*08:02_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*08:02_9.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*12:03_10.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*12:03_10.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*12:03_11.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*12:03_11.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*12:03_8.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*12:03_8.csv
mhcflurry-predict /data1/wuguojia/data/mhc_benchmark/testbase/csv/HLA-C*12:03_9.csv --out /data1/wuguojia/data/mhc_benchmark/testbase/result/mhcflurry/HLA-C*12:03_9.csv
