#!/bin/bash
source /data1/wuguojia/software/miniconda/etc/profile.d/conda.sh
conda activate deepnetbim
cd /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src #must turn to this directory
#----------------------------------------------------------------
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*01:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*01:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-A*01:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*02:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*02:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-A*02:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*03:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*03:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-A*03:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*11:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*11:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-A*11:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*23:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*23:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-A*23:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*24:02_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*24:02_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-A*24:02_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*25:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*25:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-A*25:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*26:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*26:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-A*26:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*30:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*30:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-A*30:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*32:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*32:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-A*32:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*33:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*33:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-A*33:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*33:03_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*33:03_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-A*33:03_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*66:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*66:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-A*66:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*68:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-A*68:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-A*68:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*07:02_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*07:02_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*07:02_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*08:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*08:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*08:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*13:02_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*13:02_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*13:02_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*14:02_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*14:02_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*14:02_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*15:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*15:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*15:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*15:02_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*15:02_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*15:02_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*18:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*18:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*18:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*27:05_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*27:05_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*27:05_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*27:09_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*27:09_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*27:09_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*35:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*35:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*35:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*35:02_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*35:02_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*35:02_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*35:03_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*35:03_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*35:03_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*38:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*38:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*38:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*39:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*39:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*39:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*40:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*40:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*40:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*40:02_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*40:02_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*40:02_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*41:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*41:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*41:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*44:02_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*44:02_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*44:02_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*44:03_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*44:03_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*44:03_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*49:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*49:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*49:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*51:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*51:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*51:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*53:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*53:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*53:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*57:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*57:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*57:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*58:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-B*58:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-B*58:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-C*03:04_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-C*03:04_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-C*03:04_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-C*04:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-C*04:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-C*04:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-C*05:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-C*05:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-C*05:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-C*07:01_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-C*07:01_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-C*07:01_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-C*08:02_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-C*08:02_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-C*08:02_9.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
rm -f /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt
cp /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-C*12:03_9.txt /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/sample.txt
python /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_base/1_vs_4/txt_deepnetbim/HLA-C*12:03_9.txt
cp /data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/data/result_prediction.txt /data1/wuguojia/data/mhc_benchmark/revision/02.negtive_sample_reconstruction/retest_result/1_vs_4/deepnetbim/HLA-C*12:03_9.txt
